// Declarative migration helper for the Sonus Auris Supabase schema.
//
// Preferred (Supabase declarative workflow): the desired state lives in
// `supabase/schemas/sonus_auris.sql`; let the Supabase CLI compute the diff
// against your linked/local database:
//
//   supabase db diff -f sonus_auris --schema public
//
// This script offers a self-contained fallback that does NOT need the CLI or a
// live database: it stamps the idempotent `schema/schema.sql` into a reviewable
// migration file under `supabase/migrations/`.
//
//   node src/diff.mjs                 write supabase/migrations/<utc>_sonus_auris.sql
//   node src/diff.mjs --print         print the migration SQL to stdout
//   node src/diff.mjs --supabase      delegate to `supabase db diff` (CLI required)
//
// MIGRATION SAFETY: output is for human review. Never apply automatically.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const printOnly = process.argv.includes('--print');
const useSupabase = process.argv.includes('--supabase');

if (useSupabase) {
  const result = spawnSync(
    'supabase',
    ['db', 'diff', '-f', 'sonus_auris', '--schema', 'public'],
    { cwd: root, stdio: 'inherit' },
  );
  if (result.error) {
    console.error(
      'Could not run the Supabase CLI. Install it (https://supabase.com/docs/guides/cli) ' +
        'or drop --supabase to emit the self-contained migration instead.',
    );
    process.exit(1);
  }
  process.exit(result.status ?? 0);
}

const schemaSql = readFileSync(join(root, 'schema/schema.sql'), 'utf8');
const stamp = new Date()
  .toISOString()
  .replace(/[-:T]/g, '')
  .replace(/\..*/, ''); // YYYYMMDDHHMMSS

const migration = [
  `-- ${stamp}_sonus_auris.sql`,
  '-- Declarative apply of the Sonus Auris schema (idempotent: safe to re-run).',
  '-- Generated by src/diff.mjs from schema/schema.sql (source: schema/tables.json).',
  '-- REVIEW before applying. Prefer `supabase db diff` for a true delta migration.',
  '',
  schemaSql.trimEnd(),
  '',
].join('\n');

if (printOnly) {
  process.stdout.write(migration);
  process.exit(0);
}

const outPath = join(root, 'supabase/migrations', `${stamp}_sonus_auris.sql`);
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, migration);
console.log(`wrote: ${join('supabase/migrations', `${stamp}_sonus_auris.sql`)}`);
console.log(
  'Review the SQL, then apply with `supabase db push` (or paste into the SQL editor).',
);
